#!/usr/bin/env python3
"""
Auto-add LLMGeneratedTest.swift to Xcode project
Solves: New users need to manually add test file to Xcode target
"""
import os
import sys
from pathlib import Path


def add_file_to_xcode_project(project_path: str, ui_test_target: str, project_root: str):
    """Add LLMGeneratedTest.swift to Xcode project programmatically"""
    
    # Calculate file path
    test_file_path = Path(project_root) / ui_test_target / "LLMGeneratedTest.swift"
    
    # Create placeholder file if it doesn't exist
    if not test_file_path.exists():
        print(f"Creating placeholder test file: {test_file_path}")
        test_file_path.parent.mkdir(parents=True, exist_ok=True)
        
        placeholder_content = '''import XCTest

/// This file is auto-generated by Testara
/// Generated tests will be written here
class LLMGeneratedTest: XCTestCase {
    func testPlaceholder() {
        XCTAssert(true, "Placeholder test - will be replaced by generated tests")
    }
}
'''
        test_file_path.write_text(placeholder_content)
        print(f"✅ Created: {test_file_path}")
    else:
        print(f"✅ File already exists: {test_file_path}")
    
    # Check if file is already referenced in the Xcode project
    pbxproj_path = Path(project_path) / "project.pbxproj"
    if pbxproj_path.exists():
        content = pbxproj_path.read_text()
        if "LLMGeneratedTest.swift" in content:
            print("✅ Already registered in Xcode project")
            return True

    # Try to add to Xcode project using pbxproj
    try:
        from pbxproj import XcodeProject

        print(f"\nAdding file to Xcode project: {pbxproj_path}")
        project = XcodeProject.load(str(pbxproj_path))

        rel_path = os.path.relpath(test_file_path, Path(project_path).parent)
        project.add_file(rel_path, target_name=ui_test_target)
        project.save()
        print(f"✅ Added to target '{ui_test_target}' in Xcode project")

    except Exception as e:
        print(f"\n⚠️  Could not auto-add to Xcode project: {e}")
        print("\n📝 Manual step required:")
        print(f"1. Open {project_path} in Xcode")
        print(f"2. Right-click '{ui_test_target}' folder → Add Files")
        print(f"3. Select: {test_file_path}")
        print(f"4. Make sure '{ui_test_target}' target is checked")
        # Don't fail — the file exists on disk, user can add manually
        return True

    return True


def main():
    """Run from command line or import as module"""
    import glob
    from dotenv import load_dotenv
    load_dotenv()

    project_root = os.getenv("PROJECT_ROOT")
    xcode_project = os.getenv("XCODE_PROJECT")
    ui_test_target = os.getenv("XCODE_UI_TEST_TARGET")

    # Auto-detect from PROJECT_ROOT if not explicitly set
    if project_root and not xcode_project:
        matches = glob.glob(str(Path(project_root) / "*.xcodeproj"))
        if matches:
            xcode_project = matches[0]
    if xcode_project and not ui_test_target:
        ui_test_target = Path(xcode_project).stem + "UITests"

    if not all([project_root, xcode_project, ui_test_target]):
        print("❌ Missing environment variables")
        print("Required in .env:")
        print("  - PROJECT_ROOT")
        print("(XCODE_PROJECT and XCODE_UI_TEST_TARGET are auto-detected)")
        sys.exit(1)
    
    print("🔧 Testara Setup: Adding test file to Xcode project")
    print("=" * 60)
    print(f"Project: {xcode_project}")
    print(f"Target:  {ui_test_target}")
    print(f"Root:    {project_root}")
    print()
    
    success = add_file_to_xcode_project(xcode_project, ui_test_target, project_root)
    
    if success:
        print("\n✅ Setup complete!")
        print("\nYou can now generate tests with Testara.")
        print("Generated tests will be written to LLMGeneratedTest.swift")
    else:
        print("\n⚠️  Please complete the manual steps above")
        sys.exit(1)


if __name__ == "__main__":
    main()
