#!/usr/bin/env python3
"""
Universal Xcode project setup for Testara.

Automatically configures ANY iOS project so Testara can generate and run tests.
Only requires PROJECT_ROOT — everything else is auto-detected.

Steps:
1. Find .xcodeproj in PROJECT_ROOT
2. Detect or locate UI test target
3. Create LLMGeneratedTest.swift in the UI test target folder
4. Register the file in the Xcode project (unless using synced groups)
5. Ensure the UI test target is in the scheme's test plan
"""
import glob
import json
import os
import re
import sys
import uuid
import xml.etree.ElementTree as ET
from pathlib import Path


# ---------------------------------------------------------------------------
# 1. Discovery helpers
# ---------------------------------------------------------------------------

def find_xcodeproj(project_root: str) -> str | None:
    """Find the first .xcodeproj in project_root."""
    matches = glob.glob(str(Path(project_root) / "*.xcodeproj"))
    # Filter out Pods.xcodeproj
    matches = [m for m in matches if "Pods.xcodeproj" not in m]
    return matches[0] if matches else None


def find_ui_test_target(pbxproj_text: str, xcodeproj: str) -> dict | None:
    """
    Find UI test target info from project.pbxproj content.
    Returns dict with 'name', 'id', and 'uses_synced_groups'.
    """
    lines = pbxproj_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        # Look for: productType = "com.apple.product-type.bundle.ui-testing"
        if 'product-type.bundle.ui-testing' in line:
            # Walk backwards to find the target block header
            # e.g.: A42705922A4293B30057E439 /* HackerNewsUITests */ = {
            for j in range(i - 1, max(i - 50, 0), -1):
                header_match = re.match(
                    r'\s*(\w+)\s*/\*\s*(.+?)\s*\*/\s*=\s*\{', lines[j]
                )
                if header_match:
                    target_id = header_match.group(1)
                    target_name = header_match.group(2)

                    # Check if it uses PBXFileSystemSynchronizedRootGroup (Xcode 16+)
                    uses_synced = (
                        "PBXFileSystemSynchronizedRootGroup" in pbxproj_text
                        and f"path = {target_name}" in pbxproj_text
                    )

                    return {
                        "name": target_name,
                        "id": target_id,
                        "uses_synced_groups": uses_synced,
                    }
            break
        i += 1
    return None


def find_all_schemes(xcodeproj: str) -> list[Path]:
    """Find all .xcscheme files in the project."""
    schemes_dir = Path(xcodeproj) / "xcshareddata" / "xcschemes"
    if not schemes_dir.exists():
        return []
    return list(schemes_dir.glob("*.xcscheme"))


def find_main_scheme(xcodeproj: str) -> Path | None:
    """Find the main app scheme (same name as the project)."""
    project_name = Path(xcodeproj).stem
    schemes = find_all_schemes(xcodeproj)

    # Prefer exact match with project name
    for scheme in schemes:
        if scheme.stem == project_name:
            return scheme

    # Fallback: first scheme that is NOT a test scheme
    for scheme in schemes:
        if "Test" not in scheme.stem:
            return scheme

    return schemes[0] if schemes else None


def find_test_plans(project_root: str) -> list[Path]:
    """Find all .xctestplan files in the project."""
    return list(Path(project_root).rglob("*.xctestplan"))


# ---------------------------------------------------------------------------
# 2. Test file creation
# ---------------------------------------------------------------------------

PLACEHOLDER_TEST = '''import XCTest

/// This file is auto-generated by Testara
/// Generated tests will be written here
class LLMGeneratedTest: XCTestCase {
    func testPlaceholder() {
        XCTAssert(true, "Placeholder test - will be replaced by generated tests")
    }
}
'''


def create_test_file(project_root: str, ui_test_target_name: str) -> Path:
    """Create LLMGeneratedTest.swift in the UI test target folder."""
    test_dir = Path(project_root) / ui_test_target_name
    test_file = test_dir / "LLMGeneratedTest.swift"

    if test_file.exists():
        print(f"  ✅ Test file already exists: {test_file}")
        return test_file

    test_dir.mkdir(parents=True, exist_ok=True)
    test_file.write_text(PLACEHOLDER_TEST)
    print(f"  ✅ Created test file: {test_file}")
    return test_file


# ---------------------------------------------------------------------------
# 3. Register file in Xcode project (for non-synced groups only)
# ---------------------------------------------------------------------------

def register_in_pbxproj(xcodeproj: str, ui_test_target: str, test_file: Path):
    """Add LLMGeneratedTest.swift to pbxproj if not already referenced."""
    pbxproj_path = Path(xcodeproj) / "project.pbxproj"
    content = pbxproj_path.read_text()

    if "LLMGeneratedTest.swift" in content:
        print("  ✅ Already registered in Xcode project")
        return True

    try:
        from pbxproj import XcodeProject

        project = XcodeProject.load(str(pbxproj_path))
        rel_path = os.path.relpath(test_file, Path(xcodeproj).parent)
        project.add_file(rel_path, target_name=ui_test_target)
        project.save()
        print(f"  ✅ Registered in target '{ui_test_target}'")
        return True
    except Exception as e:
        print(f"  ⚠️  Could not auto-register in Xcode project: {e}")
        print(f"     Manual step: In Xcode, add {test_file.name} to '{ui_test_target}' target")
        return False


# ---------------------------------------------------------------------------
# 4. Ensure UI test target is testable in scheme
# ---------------------------------------------------------------------------

def ensure_uitests_in_test_plan(
    project_root: str, xcodeproj: str, target_name: str, target_id: str
) -> bool:
    """Add UI test target to .xctestplan if it's missing."""
    test_plans = find_test_plans(project_root)
    if not test_plans:
        return False

    modified_any = False
    xcodeproj_name = Path(xcodeproj).name

    for plan_path in test_plans:
        try:
            plan = json.loads(plan_path.read_text())
        except (json.JSONDecodeError, OSError):
            continue

        test_targets = plan.get("testTargets", [])

        # Check if target already in test plan
        already_present = any(
            t.get("target", {}).get("name") == target_name
            for t in test_targets
        )
        if already_present:
            print(f"  ✅ '{target_name}' already in {plan_path.name}")
            continue

        # Add it
        new_entry = {
            "parallelizable": False,
            "target": {
                "containerPath": f"container:{xcodeproj_name}",
                "identifier": target_id,
                "name": target_name,
            },
        }
        test_targets.append(new_entry)
        plan["testTargets"] = test_targets

        plan_path.write_text(json.dumps(plan, indent=2) + "\n")
        print(f"  ✅ Added '{target_name}' to {plan_path.name}")
        modified_any = True

    return modified_any


def ensure_uitests_in_scheme(
    xcodeproj: str, target_name: str, target_id: str
) -> bool:
    """
    Add UI test target to the main scheme's TestAction.
    This handles schemes that use inline TestableReferences (no test plan).
    """
    scheme_path = find_main_scheme(xcodeproj)
    if not scheme_path:
        print("  ⚠️  No scheme found")
        return False

    tree = ET.parse(scheme_path)
    root = tree.getroot()
    test_action = root.find("TestAction")
    if test_action is None:
        print("  ⚠️  No TestAction in scheme")
        return False

    # If scheme uses a TestPlanReference, we handle it via test plan files instead
    test_plans_el = test_action.find("TestPlans")
    if test_plans_el is not None:
        # Test plans are handled by ensure_uitests_in_test_plan
        return False

    # Check if already has TestableReferences for our target
    testables = test_action.find("Testables")
    if testables is None:
        testables = ET.SubElement(test_action, "Testables")

    xcodeproj_name = Path(xcodeproj).name
    for testable_ref in testables.findall("TestableReference"):
        buildable_ref = testable_ref.find("BuildableReference")
        if buildable_ref is not None and buildable_ref.get("BlueprintName") == target_name:
            print(f"  ✅ '{target_name}' already in scheme {scheme_path.stem}")
            return False

    # Add TestableReference
    testable = ET.SubElement(testables, "TestableReference")
    testable.set("skipped", "NO")
    testable.set("parallelizable", "YES")

    buildable = ET.SubElement(testable, "BuildableReference")
    buildable.set("BuildableIdentifier", "primary")
    buildable.set("BlueprintIdentifier", target_id)
    buildable.set("BuildableName", f"{target_name}.xctest")
    buildable.set("BlueprintName", target_name)
    buildable.set("ReferencedContainer", f"container:{xcodeproj_name}")

    # Write with XML declaration
    tree.write(scheme_path, xml_declaration=True, encoding="UTF-8")
    print(f"  ✅ Added '{target_name}' to scheme {scheme_path.stem}")
    return True


# ---------------------------------------------------------------------------
# 5. RAG index tracking
# ---------------------------------------------------------------------------

def get_rag_index_tracker(rag_store_dir: str) -> Path:
    """Return path to the file that tracks which project was indexed."""
    return Path(rag_store_dir) / ".indexed_project"


def is_rag_reindex_needed(project_root: str, rag_store_dir: str) -> bool:
    """Check if RAG needs re-indexing (project changed or never indexed)."""
    tracker = get_rag_index_tracker(rag_store_dir)
    if not tracker.exists():
        return True
    stored = tracker.read_text().strip()
    return stored != os.path.abspath(project_root)


def mark_rag_indexed(project_root: str, rag_store_dir: str):
    """Record which project was indexed in RAG store."""
    tracker = get_rag_index_tracker(rag_store_dir)
    tracker.parent.mkdir(parents=True, exist_ok=True)
    tracker.write_text(os.path.abspath(project_root) + "\n")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def setup_project(project_root: str) -> dict:
    """
    Full automatic setup for any iOS project.
    Returns a dict with discovered settings and status.
    """
    result = {
        "success": False,
        "xcodeproj": None,
        "ui_test_target": None,
        "scheme": None,
        "test_file": None,
        "needs_reindex": False,
    }

    project_root = os.path.abspath(project_root)

    # Step 1: Find xcodeproj
    print("\n🔍 Detecting Xcode project...")
    xcodeproj = find_xcodeproj(project_root)
    if not xcodeproj:
        print("  ❌ No .xcodeproj found in PROJECT_ROOT")
        print(f"     Searched: {project_root}")
        return result
    result["xcodeproj"] = xcodeproj
    print(f"  ✅ Found: {Path(xcodeproj).name}")

    # Step 2: Find UI test target
    print("\n🔍 Detecting UI test target...")
    pbxproj_path = Path(xcodeproj) / "project.pbxproj"
    if not pbxproj_path.exists():
        print("  ❌ project.pbxproj not found")
        return result

    pbxproj_text = pbxproj_path.read_text()
    target_info = find_ui_test_target(pbxproj_text, xcodeproj)

    if not target_info:
        # No UI test target exists — provide guidance
        project_name = Path(xcodeproj).stem
        expected_target = f"{project_name}UITests"
        print(f"  ❌ No UI test target found in {Path(xcodeproj).name}")
        print(f"\n  📝 To create one in Xcode:")
        print(f"     1. Open {Path(xcodeproj).name} in Xcode")
        print(f"     2. File → New → Target → UI Testing Bundle")
        print(f"     3. Name it '{expected_target}'")
        print(f"     4. Re-run Testara setup")
        return result

    result["ui_test_target"] = target_info["name"]
    print(f"  ✅ Found: {target_info['name']} (id: {target_info['id']})")
    if target_info["uses_synced_groups"]:
        print(f"  ℹ️  Uses Xcode 16+ synced groups (auto-sync enabled)")

    # Step 3: Find main scheme
    print("\n🔍 Detecting scheme...")
    scheme = find_main_scheme(xcodeproj)
    if scheme:
        result["scheme"] = str(scheme)
        print(f"  ✅ Found: {scheme.stem}")
    else:
        print("  ⚠️  No scheme found")

    # Step 4: Create test file
    print("\n📝 Setting up test file...")
    test_file = create_test_file(project_root, target_info["name"])
    result["test_file"] = str(test_file)

    # Step 5: Register in Xcode project (skip for synced groups)
    if not target_info["uses_synced_groups"]:
        print("\n📎 Registering in Xcode project...")
        register_in_pbxproj(xcodeproj, target_info["name"], test_file)
    else:
        print("\n📎 Synced groups detected — Xcode will auto-discover the file")

    # Step 6: Ensure UI test target is in test plan / scheme
    print("\n🧪 Ensuring UI tests are in test plan...")
    plan_modified = ensure_uitests_in_test_plan(
        project_root, xcodeproj, target_info["name"], target_info["id"]
    )
    if not plan_modified:
        # Try scheme-level TestableReferences as fallback
        ensure_uitests_in_scheme(xcodeproj, target_info["name"], target_info["id"])

    # Step 7: Check RAG indexing
    rag_store = str(Path(__file__).resolve().parents[3] / "rag_store")
    result["needs_reindex"] = is_rag_reindex_needed(project_root, rag_store)
    if result["needs_reindex"]:
        print("\n📊 RAG index needs update for this project")

    result["success"] = True
    return result


def main():
    """CLI entry point."""
    from dotenv import load_dotenv
    load_dotenv()

    project_root = os.getenv("PROJECT_ROOT")
    if not project_root:
        print("❌ PROJECT_ROOT not set in .env")
        sys.exit(1)

    if not Path(project_root).is_dir():
        print(f"❌ PROJECT_ROOT does not exist: {project_root}")
        sys.exit(1)

    print("🔧 Testara Setup: Configuring Xcode project")
    print("=" * 60)
    print(f"Project root: {project_root}")

    result = setup_project(project_root)

    if result["success"]:
        print("\n" + "=" * 60)
        print("✅ Setup complete!")
        print(f"   Project:     {Path(result['xcodeproj']).name}")
        print(f"   Test target: {result['ui_test_target']}")
        print(f"   Test file:   {Path(result['test_file']).name}")
        if result["needs_reindex"]:
            print("   ⚠️  RAG re-indexing needed (will happen on next start)")
    else:
        print("\n⚠️  Setup incomplete — see messages above")
        sys.exit(1)


if __name__ == "__main__":
    main()
